sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
cache:
  directories:
    - $HOME/.m2
install: mvn install -DskipTests=false -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - echo $HOME
